### ISSUE TITLE
KeyError: 'batteryChargeLevel'

### ISSUE THREAD

**Issue by IceBotYT** [Dielee/volvo2mqtt#1]
Hi @Dielee! Thank you for this add-on, months of waiting has finally ended!

There is an issue though:
When I run it with my 2022 C40, I get this error:

```
Traceback (most recent call last):
  File "C:\Users\user\volvo2mqtt\main.py", line 7, in <module>
    update_loop()
  File "C:\Users\user\volvo2mqtt\mqtt.py", line 76, in update_loop
    update_car_data()
  File "C:\Users\user\volvo2mqtt\mqtt.py", line 105, in update_car_data
    state = volvo.api_call(sensor["url"], "GET", sensor["id"])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\volvo2mqtt\volvo.py", line 150, in api_call
    return data["data"]["batteryChargeLevel"]["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'batteryChargeLevel'
```

and I look into the data and:

`{'status': 200, 'operationId': '-------------------------', 'data': {}}` (I redacted the operation ID)

Let me know if you need any more info from me!

**Comment by Dielee** [comment]
Is your C40 a recharge model ?

**Comment by IceBotYT** [comment]
Yeah, the errors are gone but the charging-related entities are still unknown. That's weird since they list that it's supported on the API page...
![image](https://github.com/Dielee/volvo2mqtt/assets/34712694/ae33fde2-2ca7-4d48-92c7-96c13cffc466)

**Comment by IceBotYT** [comment]
> Is your C40 a recharge model ?

Yes it is.

**Comment by Dielee** [comment]
But your Volvo app works as expected?

**Comment by IceBotYT** [comment]
Yes it does.
![image](https://github.com/Dielee/volvo2mqtt/assets/34712694/c5e0c599-92b6-4c55-b8d9-d9da9b3d72e7)

**Comment by Dielee** [comment]
So there are two options: 

1. Ask the Volvo support for help.
2. Get a rooted android device and reverse engineer the connection between app and Volvo API. I will do this maybe today with my car. Maybe I can help you with your problem after this...

**Comment by IceBotYT** [comment]
1. I've already sent an email to the email listed at the bottom of the developer portal. (It's the contact button)

2. Does it have to be a physical android device or can it be an emulator? I tried it with an emulator and the Volvo app detected that it was rooted and warned me about it. It was also giving me errors when I try to sign in.

I live in North America.

**Comment by IceBotYT** [comment]
It looks like the battery charge level via the connected vehicle API does work, but the location API does not work, even though it is supported by the API

**Comment by Dielee** [comment]
If the battery charge level isn't working, your car can't interact with the energy API. Location API work for my XC40 and many others. Why it won't work for your C40 makes no sense to me.

**Comment by Dielee** [comment]
Any news here ?

**Comment by IceBotYT** [comment]
Nope. Same sensors are missing, even after switching to the owner profile

**Comment by IceBotYT** [comment]
Not stale.

**Comment by Dielee** [comment]
If not stale, what can I do for you ? This seems to be an API issue by Volvo...

**Comment by IceBotYT** [comment]
It may be. I reached out to them a couple weeks ago, yet no response.

**Comment by IceBotYT** [comment]
Sorry, just checked my e-mail, and I did get this response. Nothing else.
![image](https://github.com/Dielee/volvo2mqtt/assets/34712694/46a477e9-811e-4a3c-ad35-a6f6c98752af)

**Comment by Dielee** [comment]
This is a Volvo issue.. some users reported the same issue without any solution. Maybe this is country related...

**Comment by IceBotYT** [comment]
Update: they responded after sending another email, and this is what they had to say.

Rather disappointing, but I’m glad it’ll be focused on in the fall!!!!

![image](https://github.com/Dielee/volvo2mqtt/assets/34712694/f0c026b4-4b05-4b9f-b7f2-fbce89b1e7b3)

**Comment by Dielee** [comment]
I thought something like this. Thanks for clarifying this issue. If this will be supported by Volvo some time, just restart the addon. All missing sensors will appear.
