### ISSUE TITLE
babel.core.UnknownLocaleError: unknown locale ‘sl_SL’

### ISSUE THREAD

**Issue by zupancicmarko** [Dielee/volvo2mqtt#179]
**Describe the bug**

Throws an error when using Slovenian language.

**To Reproduce**:<br>
1. Use sl_SL in Babel locale
2. Restart
3. See Error

**Expected behavior**:<br>
Work.

**Version info**:<br>
volvo2mqtt: Current version: 1.8.27
homeassistant: Core 2024.2.5

**Logs**:<br>
Enable the debug option and upload your logfile here. <br>
```
Traceback (most recent call last):
  File "/volvoAAOS2mqtt/main.py", line 16, in <module>
    update_loop()
  File "/volvoAAOS2mqtt/mqtt.py", line 227, in update_loop
    update_car_data()
  File "/volvoAAOS2mqtt/mqtt.py", line 237, in update_car_data
    last_data_update = format_datetime(datetime.now(util.TZ), format="medium", locale=settings["babelLocale"])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/babel/dates.py", line 719, in format_datetime
    locale = Locale.parse(locale)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/babel/core.py", line 391, in parse
    raise UnknownLocaleError(input_id)
babel.core.UnknownLocaleError: unknown locale 'sl_SL'
```

**Comment by zupancicmarko** [comment]
> Please try:
> 
> sl_SI

Awesome! This works! Thanks a million! 🥳🥳🥳

**Comment by Dielee** [comment]
Yeah, nice. Thanks for the coffee ☕.
