### ISSUE TITLE
Getting Odometer Crashing

### ISSUE THREAD

**Issue by brownstone666** [Dielee/volvo2mqtt#19]
Some cars dont return odometer information, crashing the application:
```
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/odometer
Traceback (most recent call last):
  File "/volvoAAOS2mqtt/./main.py", line 9, in <module>
    update_loop()
  File "/volvoAAOS2mqtt/mqtt.py", line 84, in update_loop
    update_car_data()
  File "/volvoAAOS2mqtt/mqtt.py", line 122, in update_car_data
    state = volvo.api_call(sensor["url"], "GET", vin, sensor["id"], force_update)
  File "/volvoAAOS2mqtt/volvo.py", line 183, in api_call
    return parse_api_data(data, sensor_id)
  File "/volvoAAOS2mqtt/volvo.py", line 288, in parse_api_data
    return data["data"]["odometer"]["value"]
KeyError: 'odometer'
```

In my case XC60 23 - (Brazil), the data field return an empty array. It would be nice to check the response.

**Comment by brownstone666** [comment]
@Dielee I made a PR

**Comment by Dielee** [comment]
v1.2.1 builds. Please test!

**Comment by brownstone666** [comment]
Now is crashing in recharged status:
```
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/doors
Starting GET call against https://api.volvocars.com/energy/v1/vehicles/{0}/recharge-status
Traceback (most recent call last):
  File "D:\homeassist\_volvo2mqtt\src\main.py", line 9, in <module>
    update_loop()
  File "D:\homeassist\_volvo2mqtt\src\mqtt.py", line 84, in update_loop
    update_car_data()
  File "D:\homeassist\_volvo2mqtt\src\mqtt.py", line 122, in update_car_data
    state = volvo.api_call(sensor["url"], "GET", vin, sensor["id"], force_update)
  File "D:\homeassist\_volvo2mqtt\src\volvo.py", line 183, in api_call
    state = parse_api_data(data, sensor_id)
  File "D:\homeassist\_volvo2mqtt\src\volvo.py", line 256, in parse_api_data
    return data["data"].get("batteryChargeLevel").get("value")
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by brownstone666** [comment]
Commit bbc6ccb works like a charm! Thanks

**Comment by Dielee** [comment]
Nice, thanks for your feedback!
