### ISSUE TITLE
Update to 1.9.3 fails

### ISSUE THREAD

**Issue by geedsen** [Dielee/volvo2mqtt#201]
**Describe the bug**

Using http://homeassistant.local:8123/hassio/addon/982ee2c4_volvo2mqtt/info
When pressing update it results in this error:

![image](https://github.com/Dielee/volvo2mqtt/assets/1316595/e3cafad2-ca5f-4f9b-808d-ccffa0971a01)

**Version info**:<br>
(You have 1.8.27 installed. Click update to update to version 1.9.3)

Core 2024.6.0b8

**Comment by Dielee** [comment]
You are on B6, are u able to update the addon on the latest stable HA update ?

**Comment by geedsen** [comment]
Hi Linus, I went back to version 2024.5.5, same problem.
Cheers
 Ben
________________________________

**Comment by Dielee** [comment]
So please send me your supervisor logs from plugin install

**Comment by geedsen** [comment]
2024-06-05 15:17:25.693 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration asusrouter which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-05 15:17:25.696 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-05 15:17:25.698 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-05 15:17:25.700 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration mitsubishi_wf_rac which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-05 15:17:39.457 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
2024-06-05 15:17:41.108 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] CURRENT_HVAC_HEAT was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACAction.HEATING instead, please report it to the author of the 'localtuya' custom integration
2024-06-05 15:17:41.116 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] CURRENT_HVAC_IDLE was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACAction.IDLE instead, please report it to the author of the 'localtuya' custom integration
2024-06-05 15:17:41.124 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] HVAC_MODE_AUTO was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.AUTO instead, please report it to the author of the 'localtuya' custom integration
2024-06-05 15:17:41.132 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] HVAC_MODE_HEAT was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT instead, please report it to the author of the 'localtuya' custom integration
2024-06-05 15:17:41.140 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] HVAC_MODE_OFF was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.OFF instead, please report it to the author of the 'localtuya' custom integration
2024-06-05 15:17:41.148 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] SUPPORT_PRESET_MODE was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.PRESET_MODE instead, please report it to the author of the 'localtuya' custom integration
2024-06-05 15:17:41.158 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] SUPPORT_TARGET_TEMPERATURE was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please report it to the author of the 'localtuya' custom integration
2024-06-05 15:17:41.167 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] SUPPORT_TARGET_TEMPERATURE_RANGE was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE_RANGE instead, please report it to the author of the 'localtuya' custom integration
2024-06-05 15:17:41.175 WARNING (ImportExecutor_0) [homeassistant.const] TEMP_CELSIUS was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'localtuya' custom integration
2024-06-05 15:17:41.184 WARNING (ImportExecutor_0) [homeassistant.const] TEMP_FAHRENHEIT was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.FAHRENHEIT instead, please report it to the author of the 'localtuya' custom integration
2024-06-05 15:17:41.198 WARNING (ImportExecutor_0) [homeassistant.components.cover] SUPPORT_CLOSE was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.CLOSE instead, please report it to the author of the 'localtuya' custom integration
2024-06-05 15:17:41.207 WARNING (ImportExecutor_0) [homeassistant.components.cover] SUPPORT_OPEN was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.OPEN instead, please report it to the author of the 'localtuya' custom integration
2024-06-05 15:17:41.216 WARNING (ImportExecutor_0) [homeassistant.components.cover] SUPPORT_SET_POSITION was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.SET_POSITION instead, please report it to the author of the 'localtuya' custom integration
2024-06-05 15:17:41.224 WARNING (ImportExecutor_0) [homeassistant.components.cover] SUPPORT_STOP was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.STOP instead, please report it to the author of the 'localtuya' custom integration
2024-06-05 15:17:41.231 WARNING (ImportExecutor_0) [homeassistant.components.cover] SUPPORT_CLOSE was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.CLOSE instead, please report it to the author of the 'localtuya' custom integration
2024-06-05 15:17:41.242 WARNING (ImportExecutor_0) [homeassistant.components.cover] SUPPORT_OPEN was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.OPEN instead, please report it to the author of the 'localtuya' custom integration
2024-06-05 15:17:41.250 WARNING (ImportExecutor_0) [homeassistant.components.cover] SUPPORT_SET_POSITION was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.SET_POSITION instead, please report it to the author of the 'localtuya' custom integration
2024-06-05 15:17:41.258 WARNING (ImportExecutor_0) [homeassistant.components.cover] SUPPORT_STOP was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.STOP instead, please report it to the author of the 'localtuya' custom integration
2024-06-05 15:17:41.285 WARNING (ImportExecutor_0) [homeassistant.components.fan] SUPPORT_DIRECTION was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use FanEntityFeature.DIRECTION instead, please report it to the author of the 'localtuya' custom integration
2024-06-05 15:17:41.292 WARNING (ImportExecutor_0) [homeassistant.components.fan] SUPPORT_OSCILLATE was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use FanEntityFeature.OSCILLATE instead, please report it to the author of the 'localtuya' custom integration
2024-06-05 15:17:41.300 WARNING (ImportExecutor_0) [homeassistant.components.fan] SUPPORT_SET_SPEED was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use FanEntityFeature.SET_SPEED instead, please report it to the author of the 'localtuya' custom integration
2024-06-05 15:17:41.309 WARNING (ImportExecutor_0) [homeassistant.components.fan] SUPPORT_DIRECTION was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use FanEntityFeature.DIRECTION instead, please report it to the author of the 'localtuya' custom integration
2024-06-05 15:17:41.316 WARNING (ImportExecutor_0) [homeassistant.components.fan] SUPPORT_OSCILLATE was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use FanEntityFeature.OSCILLATE instead, please report it to the author of the 'localtuya' custom integration
2024-06-05 15:17:41.326 WARNING (ImportExecutor_0) [homeassistant.components.fan] SUPPORT_SET_SPEED was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use FanEntityFeature.SET_SPEED instead, please report it to the author of the 'localtuya' custom integration
2024-06-05 15:17:41.732 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'localtuya' accesses hass.helpers.service. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from service directly at custom_components/localtuya/__init__.py, line 164: hass.helpers.service.async_register_admin_service(, please create a bug report at https://github.com/rospogrigio/localtuya/issues
2024-06-05 15:17:42.323 WARNING (ImportExecutor_0) [homeassistant.helpers.typing] HomeAssistantType was used from mitsubishi_wf_rac, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'mitsubishi_wf_rac' custom integration
2024-06-05 15:17:42.347 WARNING (ImportExecutor_0) [homeassistant.helpers.typing] HomeAssistantType was used from mitsubishi_wf_rac, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'mitsubishi_wf_rac' custom integration
2024-06-05 15:17:42.504 WARNING (ImportExecutor_0) [homeassistant.helpers.typing] HomeAssistantType was used from mitsubishi_wf_rac, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'mitsubishi_wf_rac' custom integration
2024-06-05 15:17:45.877 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.12/site-packages/plexapi/base.py:183: SyntaxWarning: invalid escape sequence '\d'
""" Load the specified key to find and build all items with the specified tag
2024-06-05 15:17:46.769 WARNING (ImportExecutor_0) [homeassistant.helpers.typing] HomeAssistantType was used from mitsubishi_wf_rac, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'mitsubishi_wf_rac' custom integration
2024-06-05 15:18:01.705 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547926584640] Unexpected exception
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 168, in async_install
await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 59, in _wrapper
data = await funct(*argv, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 136, in async_update_addon
return await hassio.send_command(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 593, in send_command
raise HassioAPIError(error.get(ATTR_MESSAGE))
homeassistant.components.hassio.handler.HassioAPIError: The command '/bin/ash -o pipefail -c apk add --no-cache python3 bash py3-pip' returned a non-zero code: 3
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
response = await hass.services.async_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2738, in async_call
response_data = await coro
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2779, in _execute_service
return await target(service_call)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in entity_service_call
single_response = await _handle_entity_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1047, in _handle_entity_call
result = await task
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 157, in async_install
await entity.async_install_with_progress(version, backup)
File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 461, in async_install_with_progress
await self.async_install(version, backup)
File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 170, in async_install
raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating Volvo2Mqtt: The command '/bin/ash -o pipefail -c apk add --no-cache python3 bash py3-pip' returned a non-zero code: 3
2024-06-05 15:18:05.038 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 642: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues
2024-06-05 15:18:33.123 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547926584640] Unexpected exception
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 168, in async_install
await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 59, in _wrapper
data = await funct(*argv, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 136, in async_update_addon
return await hassio.send_command(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 593, in send_command
raise HassioAPIError(error.get(ATTR_MESSAGE))
homeassistant.components.hassio.handler.HassioAPIError: The command '/bin/ash -o pipefail -c apk add --no-cache python3 bash py3-pip' returned a non-zero code: 3
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
response = await hass.services.async_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2738, in async_call
response_data = await coro
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2779, in _execute_service
return await target(service_call)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in entity_service_call
single_response = await _handle_entity_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1047, in _handle_entity_call
result = await task
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 157, in async_install
await entity.async_install_with_progress(version, backup)
File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 461, in async_install_with_progress
await self.async_install(version, backup)
File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 170, in async_install
raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating Volvo2Mqtt: The command '/bin/ash -o pipefail -c apk add --no-cache python3 bash py3-pip' returned a non-zero code: 3
2024-06-05 15:18:56.840 WARNING (MainThread) [homeassistant.helpers.entity] Update of climate.airco is taking over 10 seconds
2024-06-05 15:20:10.431 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.volvo_yv1xzedv6p2944143_estimated_charging_time (min) cannot be converted to the unit of previously compiled statistics (minutes). Generation of long term statistics will be suppressed unless the unit changes back to minutes or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2024-06-05 15:26:56.854 WARNING (MainThread) [homeassistant.helpers.entity] Update of climate.airco is taking over 10 seconds
2024-06-05 15:27:17.430 ERROR (MainThread) [custom_components.mitsubishi_wf_rac.wfrac.device] Error: something went wrong updating the airco [Airco] values
________________________________

**Comment by westlund** [comment]
I have almost the same error, reurns 2 instead of 3. I'm submitting my supervisor log below.

```
2024-06-07 10:37:09.369 INFO (MainThread) [supervisor.docker.addon] Updating image 982ee2c4/aarch64-addon-volvo2mqtt:1.8.27 to 982ee2c4/aarch64-addon-volvo2mqtt:1.9.3
2024-06-07 10:37:09.372 INFO (MainThread) [supervisor.docker.addon] Starting build for 982ee2c4/aarch64-addon-volvo2mqtt:1.9.3
2024-06-07 10:37:21.419 ERROR (MainThread) [supervisor.docker.addon] Can't build 982ee2c4/aarch64-addon-volvo2mqtt:1.9.3: The command '/bin/ash -o pipefail -c apk add --no-cache python3 bash py3-pip' returned a non-zero code: 2
2024-06-07 10:37:21.419 ERROR (MainThread) [supervisor.docker.addon] Build log: 
Step 1/15 : ARG BUILD_FROM


Step 2/15 : FROM $BUILD_FROM


 ---> 3050c2ba69b9

Step 3/15 : RUN apk add --no-cache python3 bash py3-pip


 ---> Running in 586a5ddeaede

fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/main/aarch64/APKINDEX.tar.gz

WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.20/main: temporary error (try again later)

fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/community/aarch64/APKINDEX.tar.gz

WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.20/community: temporary error (try again later)
ERROR: unable to select packages:
  py3-pip (no such package):
    required by: world[py3-pip]
  python3 (no such package):
    required by: world[python3]

 ---> Removed intermediate container 586a5ddeaede
```

**Comment by Dielee** [comment]
So it looks like the apline base container isn't available at this time. As said in the message, please try again later. 
This isn't a volvo2mqtt issue....

**Comment by westlund** [comment]
Yes, I can download it from my HA server:

```
➜  ~ wget https://dl-cdn.alpinelinux.org/alpine/v3.20/main/aarch64/APKINDEX.tar.gz                                  
--2024-06-08 09:16:52--  https://dl-cdn.alpinelinux.org/alpine/v3.20/main/aarch64/APKINDEX.tar.gz
Resolving dl-cdn.alpinelinux.org (dl-cdn.alpinelinux.org)... 151.101.86.132, 2a04:4e42:14::644
Connecting to dl-cdn.alpinelinux.org (dl-cdn.alpinelinux.org)|151.101.86.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 473156 (462K) [application/octet-stream]
Saving to: 'APKINDEX.tar.gz'

APKINDEX.tar.gz                          100%[===============================================================================>] 462.07K  --.-KB/s    in 0.02s   

2024-06-08 09:16:52 (20.0 MB/s) - 'APKINDEX.tar.gz' saved [473156/473156]
```

**Comment by Dielee** [comment]
And addon install isn't working?

**Comment by geedsen** [comment]
Still not for me.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Dielee** [comment]
This looks like a local problem, for me everything is working. I don't know why your updates don't work.

**Comment by geedsen** [comment]
And now it just worked...

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by westlund** [comment]
I tried an uninstall, which worked. Then, whenre- installing, I get the same error as when updating :-( I'll start going through my logs to see if Alpine is referenced from or mentioned somewhere else.

**Comment by geedsen** [comment]
It now just worked for me...

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by geedsen** [comment]
According to the log I had data for about 6 hours, since then I have this: 
![image](https://github.com/Dielee/volvo2mqtt/assets/1316595/19336392-5203-47d4-acca-e48231e9be60)

**Comment by Dielee** [comment]
If you have an issue, please open up a new issue and provide logs!

**Comment by geedsen** [comment]
Sorry, I thought that only went to you, not github.

**Comment by westlund** [comment]
The error persisted for about one week so I gave up after tracing log files and relationships to other libraries, considering my next step. Then, suddenly and without any changes to Home Assistant (by me) the update was successful.

**Comment by westlund** [comment]
This bug has re-emerged, I get

`The command '/bin/ash -o pipefail -c apk add --no-cache python3 bash py3-pip' returned a non-zero code: 2`

when I try to update from 1.9.5 to 1.9.6 :(

**Supervisor log**

```
2024-08-23 12:30:35.473 ERROR (MainThread) [supervisor.docker.addon] Can't build 982ee2c4/aarch64-addon-volvo2mqtt:1.9.6: The command '/bin/ash -o pipefail -c apk add --no-cache python3 bash py3-pip' returned a non-zero code: 2
2024-08-23 12:30:35.474 ERROR (MainThread) [supervisor.docker.addon] Build log: 
Step 1/15 : ARG BUILD_FROM


Step 2/15 : FROM $BUILD_FROM


 ---> 5323f8eef0b6

Step 3/15 : RUN apk add --no-cache python3 bash py3-pip


 ---> Running in 8e0cf987a122

fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/main/aarch64/APKINDEX.tar.gz

WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.20/main: temporary error (try again later)

fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/community/aarch64/APKINDEX.tar.gz

**WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.20/community: temporary error (try again later)**

ERROR: unable to select packages:
  py3-pip (no such package):
    required by: world[py3-pip]
  python3 (no such package):
    required by: world[python3]

 ---> Removed intermediate container 8e0cf987a122

```

**My system**
```
Core 2024.8.2
Supervisor 2024.08.0
Operating System 13.1
Frontend 20240809.0
```

The error has persisted since the 1.9.6 upgrade. At the time I was running a Home Assistant Green with Core 2024.7.0+, which I updated to Yellow restoring a backup to it.

When I try fetching https://dl-cdn.alpinelinux.org/alpine/v3.20/community/aarch64/APKINDEX.tar.gz with curl it works, I can download the file to both my HA instance as well as locally on my client (Mac OS) using

`curl -o file.tar.gz https://dl-cdn.alpinelinux.org/alpine/v3.20/community/aarch64/APKINDEX.tar.gz`

I have waited a few weeks to see if this eventually disappears, but to no avail. Any clue where to look next or if this is an issue for the core or supervisor teams?

/ Mike
