### ISSUE TITLE
Can not create container

### ISSUE THREAD

**Issue by pacsabi** [Dielee/volvo2mqtt#21]
I can not deploy. When I try to run docker run getting the following error: 
latest: Pulling from dielee/volvo2mqtt
Digest: sha256:d471b459c12cbc9daf5235610ghtrr2d23a2dbe2ae2d9e7234ce9e5b9499301
Status: Image is up to date for ghcr.io/dielee/volvo2mqtt:latest
Starting volvo2mqtt version v1.2.2
Vin: ['YV1UZBFVDxxxxxxxxx'] found!
Traceback (most recent call last):
  File "/volvoAAOS2mqtt/./main.py", line 8, in <module>
    connect()
  File "/volvoAAOS2mqtt/mqtt.py", line 26, in connect
    client.connect(settings["mqtt"]["broker"])
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/local/lib/python3.9/socket.py", line 823, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

**Comment by Dielee** [comment]
Pls show your mqtt config

**Comment by pacsabi** [comment]
Thank you! The config:
<img width="578" alt="Screenshot 2023-06-22 at 21 20 11" src="https://github.com/Dielee/volvo2mqtt/assets/79047425/abfdedd7-1332-44ce-968e-06af94bff3ef">
<img width="439" alt="Screenshot 2023-06-22 at 21 22 32" src="https://github.com/Dielee/volvo2mqtt/assets/79047425/7453502f-a907-42ec-b993-c41a939b77ea">

**Comment by pacsabi** [comment]
Meanwhile it is working. I made a mistake, included :1883 port in the config and it was not necessary

**Comment by Dielee** [comment]
Which car do you have ?

**Comment by pacsabi** [comment]
XC60 early 2022 PHEV
You did a very good job, thank you very much!
