### ISSUE TITLE
OTP token is not deleted when uninstalling addon

### ISSUE THREAD

**Issue by kristofferbj** [Dielee/volvo2mqtt#228]
I have a new Volvo Id but cannot use it in the addon since the OTP token is connected to my old Volvo Id and there seems to be no way to delete the old token. Even when I uninstall and reinstall the addon, the token is still there. The result is that I never get any new OTP code in my e-mail. Instead I get this stacktrace:

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Sep 11 14:13:42 volvo2mqtt [106] - INFO: Starting volvo2mqtt version v1.9.6
Sep 11 14:13:42 volvo2mqtt [106] - DEBUG: MQTT Credentials - Host core-mosquitto Port: 1883 User: xxxPass: xxx
Sep 11 14:13:42 volvo2mqtt [106] - **INFO: Using login from token file**
Sep 11 14:13:42 volvo2mqtt [106] - INFO: Refreshing credentials
Sep 11 14:13:42 volvo2mqtt [106] - DEBUG: VCCAPIKEY xxxworks!
Sep 11 14:13:42 volvo2mqtt [106] - DEBUG: [{'key': 'xxx', 'extended': False, 'extended_until': None, 'in_use': False}]
Sep 11 14:13:42 volvo2mqtt [106] - INFO: Using VCCAPIKEY: xxx
Sep 11 14:13:42 volvo2mqtt [106] - DEBUG: [{'key': 'xxx', 'extended': False, 'extended_until': None, 'in_use': True}]
Traceback (most recent call last):
  File "/volvoAAOS2mqtt/main.py", line 15, in <module>
    authorize()
  File "/volvoAAOS2mqtt/volvo.py", line 106, in authorize
    get_vehicles()
  File "/volvoAAOS2mqtt/volvo.py", line 214, in get_vehicles
    raise Exception("No vehicle in account " + settings.volvoData["username"] + " found.")
Exception: No vehicle in account x@x.x found.
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped`

**Comment by kristofferbj** [comment]
Thank you, now it works.
