### ISSUE TITLE
HA - Babel Locale bug?

### ISSUE THREAD

**Issue by larronni** [Dielee/volvo2mqtt#24]
When trying to set Babel locale = no_NO (as stated on https://www.ibm.com/docs/en/radfws/9.7?topic=overview-locales-code-pages-supported for Norway), the addon fails to start with error:

```
Traceback (most recent call last):
  File "/volvoAAOS2mqtt/./main.py", line 9, in <module>
    update_loop()
  File "/volvoAAOS2mqtt/mqtt.py", line 84, in update_loop
    update_car_data()
  File "/volvoAAOS2mqtt/mqtt.py", line 91, in update_car_data
    last_data_update = format_datetime(datetime.now(), format="medium", locale=settings["babelLocale"])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/babel/dates.py", line 719, in format_datetime
    locale = Locale.parse(locale)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/babel/core.py", line 391, in parse
    raise UnknownLocaleError(input_id)
babel.core.UnknownLocaleError: unknown locale 'no_NO'
```

Setting it to en_GB works

**Comment by Dielee** [comment]
Yeah, babel seems to be a bit strange some times... Just use `no` please.

**Comment by Dielee** [comment]
Works ? If yes, please close.

**Comment by larronni** [comment]
Works to set babel to `no`
