### ISSUE TITLE
No OTP found, exting...

### ISSUE THREAD

**Issue by darek203** [Dielee/volvo2mqtt#257]
**Describe the bug**
Add-on stopped working few days ago. I've updated it to the latest version (1.10.5) but for some reason it doesn't authenthicate properly. Whenever I'm running it or restarting it asks for OTP which I'm updating trough developer tools but no success.

I have already restarted HA, reinstalled add-on but still the same problem is there.

**Version info**:<br>
HA installed on virtual machine under Windows.

**Logs**:<br>
Oct 28 12:46:03 volvo2mqtt [106] - INFO: Waiting for otp code... Please check your mailbox and post your otp code to the following mqtt topic "volvoAAOS2mqtt/otp_code". Retry 22/24
Oct 28 12:46:08 volvo2mqtt [106] - INFO: Waiting for otp code... Please check your mailbox and post your otp code to the following mqtt topic "volvoAAOS2mqtt/otp_code". Retry 23/24
Traceback (most recent call last):
  File "/volvoAAOS2mqtt/main.py", line 15, in <module>
    authorize()
  File "/volvoAAOS2mqtt/volvo.py", line 46, in authorize
    refresh_auth()
  File "/volvoAAOS2mqtt/volvo.py", line 203, in refresh_auth
    authorize(renew_tokenfile=True)
  File "/volvoAAOS2mqtt/volvo.py", line 77, in authorize
    response = send_otp(auth_session, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volvoAAOS2mqtt/volvo.py", line 161, in send_otp
    raise Exception ("No OTP found, exting...")
Exception: No OTP found, exting...

**Comment by darek203** [comment]
ok, nevermind... I've managed to fix it by publishing the OTP code via MQTT - publishing topic with verification code in payload... closing.
