### ISSUE TITLE
Updates stop after exception to Volvo servers

### ISSUE THREAD

**Issue by ivanfmartinez** [Dielee/volvo2mqtt#265]
**Describe the bug**
In last days sometimes the entities became unavailable sometimes, after checking the logs I found that this happen after connection exceptions .

When I restart the docker container it updates again.

Apparently there are some times when there are exceptions and it keeps updating.

I have started now the container with CONF_debug: true and will update with more logs when happen again

**To Reproduce**:<br>
Unable to reproduce manually, apparently it happens when there is a connection error to the volvo servers

**Expected behavior**:<br>
The volvo2mqtt should retry and keep updating status

**Version info**:<br>
Running v1.10.5 on docker with mosquitto server

**Logs**:<br>
```
volvo2mqtt    | Exception in thread Thread-1:
volvo2mqtt    | Traceback (most recent call last):
volvo2mqtt    |   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 536, in _make_request
volvo2mqtt    |     response = conn.getresponse()
volvo2mqtt    |   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 507, in getresponse
volvo2mqtt    |     httplib_response = super().getresponse()
volvo2mqtt    |   File "/usr/local/lib/python3.9/http/client.py", line 1377, in getresponse
volvo2mqtt    |     response.begin()
volvo2mqtt    |   File "/usr/local/lib/python3.9/http/client.py", line 320, in begin
volvo2mqtt    |     version, status, reason = self._read_status()
volvo2mqtt    |   File "/usr/local/lib/python3.9/http/client.py", line 281, in _read_status
volvo2mqtt    |     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
volvo2mqtt    |   File "/usr/local/lib/python3.9/socket.py", line 716, in readinto
volvo2mqtt    |     return self._sock.recv_into(b)
volvo2mqtt    |   File "/usr/local/lib/python3.9/ssl.py", line 1275, in recv_into
volvo2mqtt    |     return self.read(nbytes, buffer)
volvo2mqtt    |   File "/usr/local/lib/python3.9/ssl.py", line 1133, in read
volvo2mqtt    |     return self._sslobj.read(len, buffer)
volvo2mqtt    | socket.timeout: The read operation timed out
volvo2mqtt    | 
volvo2mqtt    | The above exception was the direct cause of the following exception:
volvo2mqtt    | 
volvo2mqtt    | Traceback (most recent call last):
volvo2mqtt    |   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 667, in send
volvo2mqtt    |     resp = conn.urlopen(
volvo2mqtt    |   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 843, in urlopen
volvo2mqtt    |     retries = retries.increment(
volvo2mqtt    |   File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 474, in increment
volvo2mqtt    |     raise reraise(type(error), error, _stacktrace)
volvo2mqtt    |   File "/usr/local/lib/python3.9/site-packages/urllib3/util/util.py", line 39, in reraise
volvo2mqtt    |     raise value
volvo2mqtt    |   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 789, in urlopen
volvo2mqtt    |     response = self._make_request(
volvo2mqtt    |   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 538, in _make_request
volvo2mqtt    |     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
volvo2mqtt    |   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 369, in _raise_timeout
volvo2mqtt    |     raise ReadTimeoutError(
volvo2mqtt    | urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='public-developer-portal-bff.weu-prod.ecpaz.volvocars.biz', port=443): Read timed out. (read timeout=15)
volvo2mqtt    | 
volvo2mqtt    | During handling of the above exception, another exception occurred:
volvo2mqtt    | 
volvo2mqtt    | Traceback (most recent call last):
volvo2mqtt    |   File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
volvo2mqtt    |     self.run()
volvo2mqtt    |   File "/usr/local/lib/python3.9/threading.py", line 917, in run
volvo2mqtt    |     self._target(*self._args, **self._kwargs)
volvo2mqtt    |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
volvo2mqtt    |     self.loop_forever(retry_first_connection=True)
volvo2mqtt    |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
volvo2mqtt    |     rc = self._loop(timeout)
volvo2mqtt    |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1164, in _loop
volvo2mqtt    |     rc = self.loop_read()
volvo2mqtt    |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1556, in loop_read
volvo2mqtt    |     rc = self._packet_read()
volvo2mqtt    |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
volvo2mqtt    |     rc = self._packet_handle()
volvo2mqtt    |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
volvo2mqtt    |     return self._handle_publish()
volvo2mqtt    |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
volvo2mqtt    |     self._handle_on_message(message)
volvo2mqtt    |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
volvo2mqtt    |     on_message(self, self._userdata, message)
volvo2mqtt    |   File "/volvoAAOS2mqtt/mqtt.py", line 170, in on_message
volvo2mqtt    |     update_car_data(True)
volvo2mqtt    |   File "/volvoAAOS2mqtt/mqtt.py", line 315, in update_car_data
volvo2mqtt    |     state = volvo.get_backend_status()
volvo2mqtt    |   File "/volvoAAOS2mqtt/volvo.py", line 449, in get_backend_status
volvo2mqtt    |     response = session.get(API_BACKEND_STATUS, timeout=15)
volvo2mqtt    |   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 602, in get
volvo2mqtt    |     return self.request("GET", url, **kwargs)
volvo2mqtt    |   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
volvo2mqtt    |     resp = self.send(prep, **send_kwargs)
volvo2mqtt    |   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
volvo2mqtt    |     r = adapter.send(request, **kwargs)
volvo2mqtt    |   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 713, in send
volvo2mqtt    |     raise ReadTimeout(e, request=request)
volvo2mqtt    | requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='public-developer-portal-bff.weu-prod.ecpaz.volvocars.biz', port=443): Read timed out. (read timeout=15)
volvo2mqtt    | Nov 02 23:48:13 volvo2mqtt [1] - INFO: Sending mqtt update...
volvo2mqtt    | Nov 02 23:48:13 volvo2mqtt [1] - INFO: Refreshing credentials
volvo2mqtt    | Nov 02 23:48:14 volvo2mqtt [1] - INFO: Mqtt update done. Next run in 600 seconds.
volvo2mqtt    | Nov 02 23:58:15 volvo2mqtt [1] - INFO: Sending mqtt update...
volvo2mqtt    | Nov 02 23:58:18 volvo2mqtt [1] - INFO: Mqtt update done. Next run in 600 seconds.

#   The refreshing, and sending mqtt update keep showing on the logs but not sending data to mqtt topics
#

```

**Comment by ivanfmartinez** [comment]
I made some progress debuging the problem. 

I have found that when it stops the mqtt will is activated (availability turns false)

I have enabled logging on paho-mqtt and found that it stops comunicating with MQTT server without any volvo server related exception, the volvo data still being updated, just not sent to mqtt.

Before it stops I can see the MQTT ping messages. I have added some extra debugs to see if I can find what happens, but apparently the mqtt loop Thread stopped.

```
Nov 03 16:20:49 volvo2mqtt [1] - DEBUG: Received PINGRESP
Nov 03 16:21:49 volvo2mqtt [1] - DEBUG: Sending PINGREQ
Nov 03 16:21:49 volvo2mqtt [1] - DEBUG: Received PINGRESP

```

**Comment by ivanfmartinez** [comment]
Found two places where the Exception kills Thread, I will leave my instance running for a week and send a PR if the problem is solved.

**Comment by jlpower68** [comment]
Hello,
I have the same problem. He are ly logs :
Nov 05 02:33:51 volvo2mqtt [1] - INFO: Sending mqtt update...
Nov 05 02:33:53 volvo2mqtt [1] - INFO: Mqtt update done. Next run in 300 seconds.
Nov 05 02:38:53 volvo2mqtt [1] - INFO: Sending mqtt update...
Nov 05 02:39:11 volvo2mqtt [1] - ERROR: Error getting data: HTTPSConnectionPool(host='api.volvocars.com', port=443): Read timed out. (read timeout=15)
Nov 05 02:39:11 volvo2mqtt [1] - INFO: Mqtt update done. Next run in 300 seconds.
Nov 05 02:44:11 volvo2mqtt [1] - INFO: Sending mqtt update...
Nov 05 02:44:11 volvo2mqtt [1] - INFO: Refreshing credentials

From 02:44:11 am, logs are stopped.

**Comment by ivanfmartinez** [comment]
@jlpower68  if you want to test my changes they are here :
https://github.com/ivanfmartinez/volvo2mqtt/tree/ifm_tests

and the docker image here : https://hub.docker.com/repository/docker/ivanfm/volvo2mqtt_testing/tags

for now they are working fine, I got some exceptions and the volvo2mqtt keeps running

**Comment by Dielee** [comment]
Thanks! Please create a PR i will merge!

**Comment by ivanfmartinez** [comment]
@Dielee I'm just testing a bit more to check if it will stay alive without problems and then I will do the PR in few days.

**Comment by git5any** [comment]
I have the same like you described in the first post. What I also have is that this happens after a manual "force update".
Lets say the loop (300sec) calls the API at 10:00. At 10:02 I publish PRESS on "homeassistant/button/<myVIN>_update_data/command". Data gets updated. At 10:05 the availability is set offline, the error is in the log and no data is sent to the broker anymore. However 5 min later the API is polled again without error, according to the log, but no data is sent to the broker. A restart of the container solves the problem. It also seems that the log is only written when the timer starts over, so at 10:00, 10:05, 10:10 etc. The manual ForceUpdate is not logged.
Lets see if you fixed it already. 
Thank you very much.

**Comment by jlpower68** [comment]
> @jlpower68 if you want to test my changes they are here : https://github.com/ivanfmartinez/volvo2mqtt/tree/ifm_tests
> 
> and the docker image here : https://hub.docker.com/repository/docker/ivanfm/volvo2mqtt_testing/tags
> 
> for now they are working fine, I got some exceptions and the volvo2mqtt keeps running

Hello, I have it under test for few days and it works fine. Thanks

**Comment by VendisF** [comment]
I had a similar problem, I uploaded the package from "ivanf*" and everything works. Communication does not collapse. But when trying to force the air conditioning, this error appears.

Dec 04 07:24:12 volvo2mqtt [105] - INFO: Success! Battery Charge Level is supported by your vehicle.
Dec 04 07:24:12 volvo2mqtt [105] - INFO: Success! Battery Capacity is supported by your vehicle.
Dec 04 07:24:12 volvo2mqtt [105] - INFO: Success! Electric Range is supported by your vehicle.
Dec 04 07:24:12 volvo2mqtt [105] - INFO: Success! Estimated Charging Time is supported by your vehicle.
Dec 04 07:24:12 volvo2mqtt [105] - INFO: Success! Charging System Status is supported by your vehicle.
Dec 04 07:24:12 volvo2mqtt [105] - INFO: Success! Charging Connection Status is supported by your vehicle.
Dec 04 07:24:12 volvo2mqtt [105] - INFO: Success! Estimated Charging Finish Time is supported by your vehicle.
Dec 04 07:24:12 volvo2mqtt [105] - INFO: Success! Odometer is supported by your vehicle.
Dec 04 07:24:12 volvo2mqtt [105] - INFO: Success! Last Data Update is supported by your vehicle.
Dec 04 07:24:12 volvo2mqtt [105] - INFO: Success! Active schedules is supported by your vehicle.
Dec 04 07:24:12 volvo2mqtt [105] - INFO: Success! Window Front Left is supported by your vehicle.
Dec 04 07:24:12 volvo2mqtt [105] - INFO: Success! Window Front Right is supported by your vehicle.
Dec 04 07:24:12 volvo2mqtt [105] - INFO: Success! Window Rear Left is supported by your vehicle.
Dec 04 07:24:12 volvo2mqtt [105] - INFO: Success! Window Rear Right is supported by your vehicle.
Dec 04 07:24:12 volvo2mqtt [105] - INFO: Success! Door Front Left is supported by your vehicle.
Dec 04 07:24:12 volvo2mqtt [105] - INFO: Success! Door Front Right is supported by your vehicle.
Dec 04 07:24:12 volvo2mqtt [105] - INFO: Success! Door Rear Left is supported by your vehicle.
Dec 04 07:24:12 volvo2mqtt [105] - INFO: Success! Door Rear Right is supported by your vehicle.
Dec 04 07:24:12 volvo2mqtt [105] - INFO: Success! Tailgate is supported by your vehicle.
Dec 04 07:24:12 volvo2mqtt [105] - INFO: Success! Engine Hood is supported by your vehicle.
Dec 04 07:24:12 volvo2mqtt [105] - INFO: Success! Tank Lid is supported by your vehicle.
Dec 04 07:24:12 volvo2mqtt [105] - INFO: Success! Sunroof is supported by your vehicle.
Dec 04 07:24:12 volvo2mqtt [105] - INFO: Success! Air Conditioning is supported by your vehicle.
Dec 04 07:24:12 volvo2mqtt [105] - INFO: Success! Lock state is supported by your vehicle.
Dec 04 07:24:12 volvo2mqtt [105] - INFO: Success! Force Update Data is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Location is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Tire Front Left is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Tire Front Right is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Tire Rear Left is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Tire Rear Right is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Engine State is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Failed, Fuel Level is unfortunately not supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Failed, Average Fuel Consumption is unfortunately not supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Average Energy Consumption is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Failed, Distance to Empty Tank is unfortunately not supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Distance to Empty Battery is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Average Speed is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Failed, Hours to Service is unfortunately not supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Distance to Service is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Time to Service is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Service warning status is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Washer Fluid Level warning is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! API Backend status is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Update Interval is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Failed, Warnings is unfortunately not supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Battery Charge Level is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Battery Capacity is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Electric Range is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Estimated Charging Time is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Charging System Status is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Charging Connection Status is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Estimated Charging Finish Time is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Odometer is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Last Data Update is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Active schedules is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Window Front Left is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Window Front Right is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Window Rear Left is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Window Rear Right is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Door Front Left is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Door Front Right is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Door Rear Left is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Door Rear Right is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Tailgate is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Engine Hood is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Tank Lid is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Sunroof is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Air Conditioning is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Lock state is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Force Update Data is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Location is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Tire Front Left is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Tire Front Right is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Tire Rear Left is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Tire Rear Right is supported by your vehicle.
Dec 04 07:24:14 volvo2mqtt [105] - INFO: Success! Engine State is supported by your vehicle.
Dec 04 07:24:14 volvo2mqtt [105] - INFO: Failed, Fuel Level is unfortunately not supported by your vehicle.
Dec 04 07:24:14 volvo2mqtt [105] - INFO: Failed, Average Fuel Consumption is unfortunately not supported by your vehicle.
Dec 04 07:24:14 volvo2mqtt [105] - INFO: Success! Average Energy Consumption is supported by your vehicle.
Dec 04 07:24:14 volvo2mqtt [105] - INFO: Failed, Distance to Empty Tank is unfortunately not supported by your vehicle.
Dec 04 07:24:14 volvo2mqtt [105] - INFO: Success! Distance to Empty Battery is supported by your vehicle.
Dec 04 07:24:14 volvo2mqtt [105] - INFO: Success! Average Speed is supported by your vehicle.
Dec 04 07:24:14 volvo2mqtt [105] - INFO: Failed, Hours to Service is unfortunately not supported by your vehicle.
Dec 04 07:24:14 volvo2mqtt [105] - INFO: Success! Distance to Service is supported by your vehicle.
Dec 04 07:24:14 volvo2mqtt [105] - INFO: Success! Time to Service is supported by your vehicle.
Dec 04 07:24:14 volvo2mqtt [105] - INFO: Success! Service warning status is supported by your vehicle.
Dec 04 07:24:14 volvo2mqtt [105] - INFO: Success! Washer Fluid Level warning is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Charging Connection Status is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Estimated Charging Finish Time is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Odometer is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Last Data Update is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Active schedules is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Window Front Left is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Window Front Right is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Window Rear Left is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Window Rear Right is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Door Front Left is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Door Front Right is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Door Rear Left is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Door Rear Right is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Tailgate is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Engine Hood is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Tank Lid is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Sunroof is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Air Conditioning is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Lock state is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Force Update Data is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Location is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Tire Front Left is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Tire Front Right is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Tire Rear Left is supported by your vehicle.
Dec 04 07:24:13 volvo2mqtt [105] - INFO: Success! Tire Rear Right is supported by your vehicle.
Dec 04 07:24:14 volvo2mqtt [105] - INFO: Success! Engine State is supported by your vehicle.
Dec 04 07:24:14 volvo2mqtt [105] - INFO: Failed, Fuel Level is unfortunately not supported by your vehicle.
Dec 04 07:24:14 volvo2mqtt [105] - INFO: Failed, Average Fuel Consumption is unfortunately not supported by your vehicle.
Dec 04 07:24:14 volvo2mqtt [105] - INFO: Success! Average Energy Consumption is supported by your vehicle.
Dec 04 07:24:14 volvo2mqtt [105] - INFO: Failed, Distance to Empty Tank is unfortunately not supported by your vehicle.
Dec 04 07:24:14 volvo2mqtt [105] - INFO: Success! Distance to Empty Battery is supported by your vehicle.
Dec 04 07:24:14 volvo2mqtt [105] - INFO: Success! Average Speed is supported by your vehicle.
Dec 04 07:24:14 volvo2mqtt [105] - INFO: Failed, Hours to Service is unfortunately not supported by your vehicle.
Dec 04 07:24:14 volvo2mqtt [105] - INFO: Success! Distance to Service is supported by your vehicle.
Dec 04 07:24:14 volvo2mqtt [105] - INFO: Success! Time to Service is supported by your vehicle.
Dec 04 07:24:14 volvo2mqtt [105] - INFO: Success! Service warning status is supported by your vehicle.
Dec 04 07:24:14 volvo2mqtt [105] - INFO: Success! Washer Fluid Level warning is supported by your vehicle.
Dec 04 07:24:14 volvo2mqtt [105] - INFO: Success! API Backend status is supported by your vehicle.
Dec 04 07:24:14 volvo2mqtt [105] - INFO: Success! Update Interval is supported by your vehicle.
Dec 04 07:24:14 volvo2mqtt [105] - INFO: Failed, Warnings is unfortunately not supported by your vehicle.
Dec 04 07:24:17 volvo2mqtt [105] - INFO: Sending mqtt update...
Dec 04 07:24:18 volvo2mqtt [105] - INFO: Mqtt update done. Next run in 300 seconds.
Dec 04 07:29:18 volvo2mqtt [105] - INFO: Sending mqtt update...
Dec 04 07:29:19 volvo2mqtt [105] - INFO: Mqtt update done. Next run in 300 seconds.
Dec 04 07:30:20 volvo2mqtt [105] - ERROR: Error getting data: HTTPSConnectionPool(host='api.volvocars.com', port=443): Read timed out. (read timeout=20)
Dec 04 07:34:19 volvo2mqtt [105] - INFO: Sending mqtt update...
Dec 04 07:34:21 volvo2mqtt [105] - INFO: Mqtt update done. Next run in 300 seconds.
Dec 04 07:39:21 volvo2mqtt [105] - INFO: Sending mqtt update...
Dec 04 07:39:24 volvo2mqtt [105] - INFO: Mqtt update done. Next run in 300 seconds.
Dec 04 07:44:24 volvo2mqtt [105] - INFO: Sending mqtt update...
Dec 04 07:44:26 volvo2mqtt [105] - INFO: Mqtt update done. Next run in 300 seconds.
Dec 04 07:49:26 volvo2mqtt [105] - INFO: Sending mqtt update...
Dec 04 07:49:29 volvo2mqtt [105] - INFO: Mqtt update done. Next run in 300 seconds.
Dec 04 07:53:40 volvo2mqtt [105] - INFO: Refreshing credentials
Dec 04 07:54:29 volvo2mqtt [105] - INFO: Sending mqtt update...
Dec 04 07:54:30 volvo2mqtt [105] - INFO: Mqtt update done. Next run in 300 seconds.
Dec 04 07:59:30 volvo2mqtt [105] - INFO: Sending mqtt update...
Dec 04 07:59:31 volvo2mqtt [105] - INFO: Mqtt update done. Next run in 300 seconds.
Dec 04 08:00:00 volvo2mqtt [105] - INFO: Turning climate off by timer!
Dec 04 08:00:01 volvo2mqtt [105] - ERROR: API Call failed. Status Code: 500. Error: {
  "error" : {
    "message" : "INTERNAL_SERVER_ERROR",
    "description" : "Error returned from car"
  }
}
Dec 04 08:01:01 volvo2mqtt [105] - ERROR: API Call failed. Status Code: 500. Error: {
  "error" : {
    "message" : "INTERNAL_SERVER_ERROR",
    "description" : "Error returned from car"
  }
}
Dec 04 08:02:01 volvo2mqtt [105] - ERROR: API Call failed. Status Code: 500. Error: {
  "error" : {
    "message" : "INTERNAL_SERVER_ERROR",
    "description" : "Error returned from car"
  }
}
Dec 04 08:03:00 volvo2mqtt [105] - INFO: Turning climate off by timer!
Dec 04 08:03:01 volvo2mqtt [105] - ERROR: API Call failed. Status Code: 500. Error: {
  "error" : {
    "message" : "INTERNAL_SERVER_ERROR",
    "description" : "Error returned from car"
  }
}
Dec 04 08:04:00 volvo2mqtt [105] - INFO: Turning climate off by timer!
Dec 04 08:04:01 volvo2mqtt [105] - ERROR: API Call failed. Status Code: 500. Error: {
  "error" : {
    "message" : "INTERNAL_SERVER_ERROR",
    "description" : "Error returned from car"
  }
}
Dec 04 08:04:31 volvo2mqtt [105] - INFO: Sending mqtt update...
Dec 04 08:04:33 volvo2mqtt [105] - INFO: Mqtt update done. Next run in 300 seconds.
Dec 04 08:05:00 volvo2mqtt [105] - INFO: Turning climate off by timer!
Dec 04 08:05:01 volvo2mqtt [105] - ERROR: API Call failed. Status Code: 500. Error: {
  "error" : {
    "message" : "INTERNAL_SERVER_ERROR",
    "description" : "Error returned from car"
  }
}

**Comment by ivanfmartinez** [comment]
still a problem on release

**Comment by VendisF** [comment]
**I don't know if there was a version change, but now everything works. Sometimes this error occurs, but it recovers itself.**

Dec 20 20:59:43 volvo2mqtt [106] - INFO: Mqtt update done. Next run in 300 seconds.
Dec 20 21:04:43 volvo2mqtt [106] - INFO: Sending mqtt update...
Dec 20 21:04:44 volvo2mqtt [106] - INFO: Mqtt update done. Next run in 300 seconds.
Dec 20 21:09:44 volvo2mqtt [106] - INFO: Sending mqtt update...
Dec 20 21:09:49 volvo2mqtt [106] - ERROR: Error getting data: HTTPSConnectionPool(host='api.volvocars.com', port=443): Max retries exceeded with url: /energy/v1/vehicles/YV12ZEL98RSxxxxxx/recharge-status (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
Dec 20 21:09:52 volvo2mqtt [106] - INFO: Mqtt update done. Next run in 300 seconds.
Dec 20 21:14:52 volvo2mqtt [106] - INFO: Sending mqtt update...
Dec 20 21:14:54 volvo2mqtt [106] - INFO: Mqtt update done. Next run in 300 seconds.
Dec 20 21:19:54 volvo2mqtt [106] - INFO: Sending mqtt update...

**Thank you for the integration, it helps me a lot when charging my car.

Vendis**
