### ISSUE TITLE
HA Add-on crashes

### ISSUE THREAD

**Issue by larronni** [Dielee/volvo2mqtt#39]
**Describe the bug**
After some hours the add-on crashes

**error log in add-one**
```
Error getting data: HTTPSConnectionPool(host='api.volvocars.com', port=443): Max retries exceeded with url: /location/v1/vehicles/******************/location (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb9d78c50>: Failed to establish a new connection: [Errno -3] Try again'))
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/tyres
Error getting data: HTTPSConnectionPool(host='api.volvocars.com', port=443): Max retries exceeded with url: /connected-vehicle/v2/vehicles/******************/tyres (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb9d802d0>: Failed to establish a new connection: [Errno -3] Try again'))
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/tyres
Error getting data: HTTPSConnectionPool(host='api.volvocars.com', port=443): Max retries exceeded with url: /connected-vehicle/v2/vehicles/******************/tyres (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb9d7ba90>: Failed to establish a new connection: [Errno -3] Try again'))
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/tyres
Error getting data: HTTPSConnectionPool(host='api.volvocars.com', port=443): Max retries exceeded with url: /connected-vehicle/v2/vehicles/******************/tyres (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb9d74ad0>: Failed to establish a new connection: [Errno -3] Try again'))
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/tyres
Error getting data: HTTPSConnectionPool(host='api.volvocars.com', port=443): Max retries exceeded with url: /connected-vehicle/v2/vehicles/******************/tyres (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb9d78850>: Failed to establish a new connection: [Errno -3] Try again'))
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/engine-status
Error getting data: HTTPSConnectionPool(host='api.volvocars.com', port=443): Max retries exceeded with url: /connected-vehicle/v2/vehicles/******************/engine-status (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb9d7abd0>: Failed to establish a new connection: [Errno -3] Try again'))
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/fuel
Error getting data: HTTPSConnectionPool(host='api.volvocars.com', port=443): Max retries exceeded with url: /connected-vehicle/v2/vehicles/******************/fuel (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb9d77350>: Failed to establish a new connection: [Errno -3] Try again'))
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/statistics
Error getting data: HTTPSConnectionPool(host='api.volvocars.com', port=443): Max retries exceeded with url: /connected-vehicle/v2/vehicles/******************/statistics (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb9d74ad0>: Failed to establish a new connection: [Errno -3] Try again'))
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/statistics
Error getting data: HTTPSConnectionPool(host='api.volvocars.com', port=443): Max retries exceeded with url: /connected-vehicle/v2/vehicles/******************/statistics (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb9d791d0>: Failed to establish a new connection: [Errno -3] Try again'))
Mqtt update done. Next run in 300 seconds.
Sending mqtt update...
Refreshing credentials
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Try again
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.11/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fba526250>: Failed to establish a new connection: [Errno -3] Try again
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/requests/adapters.py", line 487, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='volvoid.eu.volvocars.com', port=443): Max retries exceeded with url: /as/token.oauth2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba526250>: Failed to establish a new connection: [Errno -3] Try again'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/volvoAAOS2mqtt/./main.py", line 11, in <module>
    update_loop()
  File "/volvoAAOS2mqtt/mqtt.py", line 96, in update_loop
    update_car_data()
  File "/volvoAAOS2mqtt/mqtt.py", line 125, in update_car_data
    state = volvo.api_call(entity["url"], "GET", vin, entity["id"], force_update)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volvoAAOS2mqtt/volvo.py", line 172, in api_call
    refresh_auth()
  File "/volvoAAOS2mqtt/volvo.py", line 68, in refresh_auth
    auth = requests.post(OAUTH_URL, data=body, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/adapters.py", line 520, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='volvoid.eu.volvocars.com', port=443): Max retries exceeded with url: /as/token.oauth2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba526250>: Failed to establish a new connection: [Errno -3] Try again'))
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Version info**
1.6.0

**Comment by Dielee** [comment]
Your container can't access `volvoid.eu.volvocars.com`. This is a local problem, no problem from the addon.
Maybe your docker host does not have internet access ?

**Comment by larronni** [comment]
Aggghhh - defective SD-card
