### ISSUE TITLE
Add-on crashes because of fuelAmount conversion to int

### ISSUE THREAD

**Issue by bogdanbujdea** [Dielee/volvo2mqtt#55]
I have a Volvo XC60 2023 T8 and the integration was working before I updated from 1.6.5 to latest. It seems the fuel amount should not be an int, but a double/float (I'm not familiar with Python types, sorry)

Jul 06 00:01:30 volvo2mqtt [106] - INFO: Success! Engine State is supported by your vehicle.
Traceback (most recent call last):
  File "/volvoAAOS2mqtt/main.py", line 13, in <module>
    authorize()
  File "/volvoAAOS2mqtt/volvo.py", line 52, in authorize
    check_supported_endpoints()
  File "/volvoAAOS2mqtt/volvo.py", line 159, in check_supported_endpoints
    state = api_call(entity["url"], "GET", vin, entity["id"])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volvoAAOS2mqtt/volvo.py", line 250, in api_call
    return parse_api_data(data, sensor_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volvoAAOS2mqtt/volvo.py", line 372, in parse_api_data
    fuel_amount = int(data["fuelAmount"]["value"])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '17.8'

**Comment by bogdanbujdea** [comment]
I just noticed there's an update for this when I was getting ready to make a PR for the issue. Thanks for the fast response!
