### ISSUE TITLE
Host is unreachable

### ISSUE THREAD

**Issue by raftheunis87** [Dielee/volvo2mqtt#70]
**Describe the bug**
When starting the container, I get the following error in the logging and then the container stops working:

```
Jul 31 09:36:27 volvo2mqtt [106] - INFO: Success! Fuel Level is supported by your vehicle.
Jul 31 09:36:27 volvo2mqtt [106] - INFO: Failed, Average Fuel Consumption is unfortunately not supported by your vehicle.
Jul 31 09:36:27 volvo2mqtt [106] - INFO: Success! Distance to Empty is supported by your vehicle.
Jul 31 09:36:27 volvo2mqtt [106] - INFO: Failed, Average Speed is unfortunately not supported by your vehicle.
Traceback (most recent call last):
  File "/volvoAAOS2mqtt/main.py", line 14, in <module>
    connect()
  File "/volvoAAOS2mqtt/mqtt.py", line 36, in connect
    client.connect(settings["mqtt"]["broker"], port)
  File "/usr/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
OSError: [Errno 113] Host is unreachable
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Version info**:<br>
1.7.7 - HA Addon

**Comment by Dielee** [comment]
The addon can't connect to your mqtt broker. Chef if it's up and accessible.

**Comment by raftheunis87** [comment]
You are 100% correct.

Should have thought about that as I have been tweaking my network last week.

Resolved!
