### ISSUE TITLE
container not starting

### ISSUE THREAD

**Issue by paradix** [Dielee/volvo2mqtt#86]
**Describe the bug**
container not starting

**To Reproduce**:<br>

**Expected behavior**:<br>

**Screenshots**:<br>

**Version info**: 1.8

**Logs**:
Traceback (most recent call last):
  File "/volvoAAOS2mqtt/./main.py", line 11, in <module>
    setup_logging()
  File "/volvoAAOS2mqtt/util.py", line 53, in setup_logging
    if settings["debug"]:
  File "/usr/local/lib/python3.9/site-packages/dynaconf/utils/functional.py", line 19, in inner
    return func(self._wrapped, *args)
  File "/usr/local/lib/python3.9/site-packages/dynaconf/base.py", line 306, in __getitem__
    raise KeyError(f"{item} does not exist")
KeyError: 'debug does not exist'

**Comment by Dielee** [comment]
Please share me a screenshot from your addon config

**Comment by paradix** [comment]
![image](https://github.com/Dielee/volvo2mqtt/assets/3265277/a0092ba3-7610-467b-9d3c-563a04234719)

**Comment by paradix** [comment]
Yes, I'm using a docker instance

**Comment by paradix** [comment]
Worsk  now with 1.8.1 thnx a lot
